[workspace]
name = "eigenlayer-rs"
version = "0.1.0"
edition = "2021"


members = ["nodeapi", "signer", "services", "metrics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
